services:
  - type: web
    name: freefire-ban-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn danger:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0